name: build

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
  # The only way to simulate if-else statement
  CHECKOUT_BRANCH: ${{ github.event_name == 'push' && github.ref || 'develop' }}

jobs:

  check-code-black-isort-flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CHECKOUT_BRANCH }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64

      - name: Prepare linters
        run: pip install black isort flake8

      - name: Check code compliance with black
        run: black . --check --diff

      - name: Check code compliance with isort
        run: |
          isort . --check --diff

      - name: Check code compliance with flake8
        run: |
          flake8 .

  mirror-to-gitlab:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://git.sinergise.com/eo/applications/qgis_sentinel_hub/"
        env:
          GITLAB_HOSTNAME: "git.sinergise.com"
          GITLAB_USERNAME: "github-action"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "507"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
